server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
   
    

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 902379648225-a1tp6v14i8phooi2o11qaule2uj6es5k.apps.googleusercontent.com
            client-secret: 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
            scope: 
            - email
            - profile
            
          facebook:
            client-id: 1946827542152714
            client-secret: 9270a38e3e4c27387fb6bd6a83a26ff4
            scope: 
            - email
            - public_profile

          naver: 
            client-id: 8TCmnC_SPSOll8jlLb3f
            client-secret: JqTnXnQ5KM
            scope: 
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.
            
            